// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/lost_found/lost_found.proto

package lostfound

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LostAndFoundType int32

const (
	LostAndFoundType_Lost  LostAndFoundType = 0
	LostAndFoundType_Found LostAndFoundType = 1
)

var LostAndFoundType_name = map[int32]string{
	0: "Lost",
	1: "Found",
}

var LostAndFoundType_value = map[string]int32{
	"Lost":  0,
	"Found": 1,
}

func (x LostAndFoundType) String() string {
	return proto.EnumName(LostAndFoundType_name, int32(x))
}

func (LostAndFoundType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e1a49343fa726016, []int{0}
}

type GetBriefsReq struct {
	Before               *timestamp.Timestamp `protobuf:"bytes,1,opt,name=before,proto3" json:"before,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetBriefsReq) Reset()         { *m = GetBriefsReq{} }
func (m *GetBriefsReq) String() string { return proto.CompactTextString(m) }
func (*GetBriefsReq) ProtoMessage()    {}
func (*GetBriefsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a49343fa726016, []int{0}
}

func (m *GetBriefsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBriefsReq.Unmarshal(m, b)
}
func (m *GetBriefsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBriefsReq.Marshal(b, m, deterministic)
}
func (m *GetBriefsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBriefsReq.Merge(m, src)
}
func (m *GetBriefsReq) XXX_Size() int {
	return xxx_messageInfo_GetBriefsReq.Size(m)
}
func (m *GetBriefsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBriefsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetBriefsReq proto.InternalMessageInfo

func (m *GetBriefsReq) GetBefore() *timestamp.Timestamp {
	if m != nil {
		return m.Before
	}
	return nil
}

type GetBriefsResp struct {
	Briefs               []*LostAndFoundBrief `protobuf:"bytes,1,rep,name=briefs,proto3" json:"briefs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetBriefsResp) Reset()         { *m = GetBriefsResp{} }
func (m *GetBriefsResp) String() string { return proto.CompactTextString(m) }
func (*GetBriefsResp) ProtoMessage()    {}
func (*GetBriefsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a49343fa726016, []int{1}
}

func (m *GetBriefsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBriefsResp.Unmarshal(m, b)
}
func (m *GetBriefsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBriefsResp.Marshal(b, m, deterministic)
}
func (m *GetBriefsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBriefsResp.Merge(m, src)
}
func (m *GetBriefsResp) XXX_Size() int {
	return xxx_messageInfo_GetBriefsResp.Size(m)
}
func (m *GetBriefsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBriefsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetBriefsResp proto.InternalMessageInfo

func (m *GetBriefsResp) GetBriefs() []*LostAndFoundBrief {
	if m != nil {
		return m.Briefs
	}
	return nil
}

type LostAndFoundBrief struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  string               `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Type                 LostAndFoundType     `protobuf:"varint,3,opt,name=type,proto3,enum=xmux.lost_found.v4.LostAndFoundType" json:"type,omitempty"`
	Name                 string               `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	Location             string               `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LostAndFoundBrief) Reset()         { *m = LostAndFoundBrief{} }
func (m *LostAndFoundBrief) String() string { return proto.CompactTextString(m) }
func (*LostAndFoundBrief) ProtoMessage()    {}
func (*LostAndFoundBrief) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a49343fa726016, []int{2}
}

func (m *LostAndFoundBrief) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LostAndFoundBrief.Unmarshal(m, b)
}
func (m *LostAndFoundBrief) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LostAndFoundBrief.Marshal(b, m, deterministic)
}
func (m *LostAndFoundBrief) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LostAndFoundBrief.Merge(m, src)
}
func (m *LostAndFoundBrief) XXX_Size() int {
	return xxx_messageInfo_LostAndFoundBrief.Size(m)
}
func (m *LostAndFoundBrief) XXX_DiscardUnknown() {
	xxx_messageInfo_LostAndFoundBrief.DiscardUnknown(m)
}

var xxx_messageInfo_LostAndFoundBrief proto.InternalMessageInfo

func (m *LostAndFoundBrief) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LostAndFoundBrief) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *LostAndFoundBrief) GetType() LostAndFoundType {
	if m != nil {
		return m.Type
	}
	return LostAndFoundType_Lost
}

func (m *LostAndFoundBrief) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LostAndFoundBrief) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *LostAndFoundBrief) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type GetDetailReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDetailReq) Reset()         { *m = GetDetailReq{} }
func (m *GetDetailReq) String() string { return proto.CompactTextString(m) }
func (*GetDetailReq) ProtoMessage()    {}
func (*GetDetailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a49343fa726016, []int{3}
}

func (m *GetDetailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDetailReq.Unmarshal(m, b)
}
func (m *GetDetailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDetailReq.Marshal(b, m, deterministic)
}
func (m *GetDetailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDetailReq.Merge(m, src)
}
func (m *GetDetailReq) XXX_Size() int {
	return xxx_messageInfo_GetDetailReq.Size(m)
}
func (m *GetDetailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDetailReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetDetailReq proto.InternalMessageInfo

func (m *GetDetailReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type LostAndFoundDetail struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Type                 LostAndFoundType     `protobuf:"varint,2,opt,name=type,proto3,enum=xmux.lost_found.v4.LostAndFoundType" json:"type,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	Location             string               `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Description          string               `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Contacts             map[string]string    `protobuf:"bytes,7,rep,name=contacts,proto3" json:"contacts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Pictures             []string             `protobuf:"bytes,8,rep,name=pictures,proto3" json:"pictures,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LostAndFoundDetail) Reset()         { *m = LostAndFoundDetail{} }
func (m *LostAndFoundDetail) String() string { return proto.CompactTextString(m) }
func (*LostAndFoundDetail) ProtoMessage()    {}
func (*LostAndFoundDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a49343fa726016, []int{4}
}

func (m *LostAndFoundDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LostAndFoundDetail.Unmarshal(m, b)
}
func (m *LostAndFoundDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LostAndFoundDetail.Marshal(b, m, deterministic)
}
func (m *LostAndFoundDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LostAndFoundDetail.Merge(m, src)
}
func (m *LostAndFoundDetail) XXX_Size() int {
	return xxx_messageInfo_LostAndFoundDetail.Size(m)
}
func (m *LostAndFoundDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_LostAndFoundDetail.DiscardUnknown(m)
}

var xxx_messageInfo_LostAndFoundDetail proto.InternalMessageInfo

func (m *LostAndFoundDetail) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *LostAndFoundDetail) GetType() LostAndFoundType {
	if m != nil {
		return m.Type
	}
	return LostAndFoundType_Lost
}

func (m *LostAndFoundDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LostAndFoundDetail) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *LostAndFoundDetail) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *LostAndFoundDetail) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *LostAndFoundDetail) GetContacts() map[string]string {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func (m *LostAndFoundDetail) GetPictures() []string {
	if m != nil {
		return m.Pictures
	}
	return nil
}

type AddItemReq struct {
	Type                 LostAndFoundType     `protobuf:"varint,1,opt,name=type,proto3,enum=xmux.lost_found.v4.LostAndFoundType" json:"type,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Location             string               `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Description          string               `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Contacts             map[string]string    `protobuf:"bytes,6,rep,name=contacts,proto3" json:"contacts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AddItemReq) Reset()         { *m = AddItemReq{} }
func (m *AddItemReq) String() string { return proto.CompactTextString(m) }
func (*AddItemReq) ProtoMessage()    {}
func (*AddItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a49343fa726016, []int{5}
}

func (m *AddItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddItemReq.Unmarshal(m, b)
}
func (m *AddItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddItemReq.Marshal(b, m, deterministic)
}
func (m *AddItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddItemReq.Merge(m, src)
}
func (m *AddItemReq) XXX_Size() int {
	return xxx_messageInfo_AddItemReq.Size(m)
}
func (m *AddItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddItemReq proto.InternalMessageInfo

func (m *AddItemReq) GetType() LostAndFoundType {
	if m != nil {
		return m.Type
	}
	return LostAndFoundType_Lost
}

func (m *AddItemReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddItemReq) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *AddItemReq) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *AddItemReq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AddItemReq) GetContacts() map[string]string {
	if m != nil {
		return m.Contacts
	}
	return nil
}

type DeleteItemReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteItemReq) Reset()         { *m = DeleteItemReq{} }
func (m *DeleteItemReq) String() string { return proto.CompactTextString(m) }
func (*DeleteItemReq) ProtoMessage()    {}
func (*DeleteItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a49343fa726016, []int{6}
}

func (m *DeleteItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteItemReq.Unmarshal(m, b)
}
func (m *DeleteItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteItemReq.Marshal(b, m, deterministic)
}
func (m *DeleteItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteItemReq.Merge(m, src)
}
func (m *DeleteItemReq) XXX_Size() int {
	return xxx_messageInfo_DeleteItemReq.Size(m)
}
func (m *DeleteItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteItemReq proto.InternalMessageInfo

func (m *DeleteItemReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterEnum("xmux.lost_found.v4.LostAndFoundType", LostAndFoundType_name, LostAndFoundType_value)
	proto.RegisterType((*GetBriefsReq)(nil), "xmux.lost_found.v4.GetBriefsReq")
	proto.RegisterType((*GetBriefsResp)(nil), "xmux.lost_found.v4.GetBriefsResp")
	proto.RegisterType((*LostAndFoundBrief)(nil), "xmux.lost_found.v4.LostAndFoundBrief")
	proto.RegisterType((*GetDetailReq)(nil), "xmux.lost_found.v4.GetDetailReq")
	proto.RegisterType((*LostAndFoundDetail)(nil), "xmux.lost_found.v4.LostAndFoundDetail")
	proto.RegisterMapType((map[string]string)(nil), "xmux.lost_found.v4.LostAndFoundDetail.ContactsEntry")
	proto.RegisterType((*AddItemReq)(nil), "xmux.lost_found.v4.AddItemReq")
	proto.RegisterMapType((map[string]string)(nil), "xmux.lost_found.v4.AddItemReq.ContactsEntry")
	proto.RegisterType((*DeleteItemReq)(nil), "xmux.lost_found.v4.DeleteItemReq")
}

func init() {
	proto.RegisterFile("proto/lost_found/lost_found.proto", fileDescriptor_e1a49343fa726016)
}

var fileDescriptor_e1a49343fa726016 = []byte{
	// 657 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x55, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xfd, 0xfc, 0x93, 0xd4, 0xb9, 0x69, 0xaa, 0x7c, 0x23, 0x44, 0x8d, 0x2b, 0xd1, 0xd4, 0xfc,
	0x14, 0x45, 0xc8, 0x91, 0x42, 0x17, 0x11, 0x88, 0x45, 0x4c, 0x4b, 0x85, 0x84, 0x10, 0xb2, 0xca,
	0x86, 0x0d, 0x72, 0xe2, 0x49, 0x65, 0xf0, 0x1f, 0xf6, 0xb8, 0x6a, 0x1e, 0x82, 0x35, 0x52, 0x1f,
	0x83, 0x57, 0xe0, 0x01, 0x78, 0x19, 0x56, 0x59, 0x31, 0x1e, 0xdb, 0xc9, 0x38, 0x49, 0x09, 0x94,
	0xdd, 0xbd, 0x77, 0xee, 0x3d, 0xb9, 0xe7, 0x9c, 0xf1, 0x04, 0x0e, 0xa2, 0x38, 0x24, 0x61, 0xcf,
	0x0b, 0x13, 0xf2, 0x61, 0x12, 0xa6, 0x81, 0xc3, 0x85, 0x06, 0x3b, 0x43, 0xe8, 0xd2, 0x4f, 0x2f,
	0x0d, 0xae, 0x7c, 0x71, 0xa4, 0xed, 0x9d, 0x87, 0xe1, 0xb9, 0x87, 0x7b, 0xac, 0x63, 0x94, 0x4e,
	0x7a, 0xd8, 0x8f, 0xc8, 0x34, 0x1f, 0xd0, 0xf6, 0x97, 0x0f, 0x89, 0xeb, 0xe3, 0x84, 0xd8, 0x7e,
	0x54, 0x34, 0xec, 0x5e, 0xd8, 0x9e, 0xeb, 0xd8, 0x04, 0xf7, 0xca, 0x20, 0x3f, 0xd0, 0x4d, 0xd8,
	0x3e, 0xc5, 0xc4, 0x8c, 0x5d, 0x3c, 0x49, 0x2c, 0xfc, 0x19, 0xf5, 0xa1, 0x3e, 0xc2, 0x93, 0x30,
	0xc6, 0xaa, 0xd0, 0x11, 0x1e, 0x35, 0xfb, 0x9a, 0x91, 0x43, 0x1b, 0x25, 0xb4, 0x71, 0x56, 0x42,
	0x5b, 0x45, 0xa7, 0xfe, 0x06, 0x5a, 0x1c, 0x46, 0x12, 0xa1, 0xe7, 0x14, 0x84, 0x65, 0x14, 0x44,
	0xa2, 0x20, 0x0f, 0x8c, 0x55, 0x42, 0xc6, 0x6b, 0x9a, 0x0d, 0x03, 0xe7, 0x65, 0x96, 0xb3, 0x59,
	0xab, 0x18, 0xd2, 0x7f, 0x08, 0xf0, 0xff, 0xca, 0x29, 0xda, 0x01, 0xd1, 0x75, 0xd8, 0x56, 0x0d,
	0x8b, 0x46, 0xa8, 0x0d, 0x52, 0x4a, 0x0b, 0x22, 0x2b, 0x64, 0x21, 0x1a, 0x80, 0x4c, 0xa6, 0x11,
	0x56, 0x25, 0x5a, 0xda, 0xe9, 0xdf, 0xdf, 0xf4, 0xa3, 0x67, 0xb4, 0xd7, 0x62, 0x13, 0x08, 0x81,
	0x1c, 0xd8, 0x3e, 0x56, 0x65, 0x06, 0xc6, 0x62, 0x64, 0x50, 0x34, 0x4a, 0x55, 0xad, 0x6d, 0xd4,
	0x81, 0xf5, 0x21, 0x0d, 0x14, 0x2f, 0x1c, 0xdb, 0xc4, 0x0d, 0x03, 0xb5, 0xce, 0x70, 0xe6, 0xb9,
	0x7e, 0xc8, 0x54, 0x3e, 0xc6, 0xc4, 0x76, 0xbd, 0x4c, 0xe5, 0xdd, 0x05, 0x17, 0x73, 0x6b, 0x66,
	0xca, 0xb1, 0xa8, 0xde, 0xc9, 0x48, 0xe9, 0x5f, 0x24, 0x40, 0xfc, 0x8e, 0xf9, 0x48, 0xc9, 0x55,
	0x58, 0xe5, 0x2a, 0xde, 0x98, 0xab, 0xb4, 0x86, 0xab, 0x7c, 0x03, 0xae, 0xb5, 0x2a, 0x57, 0xd4,
	0x81, 0xa6, 0x83, 0x93, 0x71, 0xec, 0x46, 0x9c, 0x14, 0x7c, 0x09, 0xbd, 0x05, 0x65, 0x1c, 0x06,
	0xc4, 0x1e, 0x93, 0x44, 0xdd, 0x62, 0x17, 0xe4, 0x68, 0xd3, 0xfe, 0xb9, 0x0e, 0xc6, 0x8b, 0x62,
	0xec, 0x24, 0x20, 0xf1, 0xd4, 0x9a, 0xa3, 0x64, 0xfb, 0x44, 0xee, 0x98, 0xa4, 0x31, 0x4e, 0x54,
	0x85, 0x22, 0xd2, 0x7d, 0xca, 0x5c, 0x7b, 0x06, 0xad, 0xca, 0x58, 0x26, 0xe6, 0x27, 0x3c, 0x2d,
	0xc5, 0xa4, 0x21, 0xba, 0x05, 0x35, 0xfa, 0x59, 0xa4, 0xb8, 0xb8, 0x4c, 0x79, 0xf2, 0x54, 0x1c,
	0x08, 0xfa, 0x57, 0x09, 0x60, 0xe8, 0x38, 0xaf, 0x08, 0xf6, 0x33, 0xdf, 0x4a, 0xd5, 0x85, 0xbf,
	0x56, 0x7d, 0xaf, 0x50, 0x5d, 0xe4, 0x3d, 0xef, 0x17, 0xf2, 0x0f, 0x0a, 0xf9, 0xa5, 0x4d, 0xf2,
	0x9b, 0xca, 0xcc, 0xac, 0x7d, 0x13, 0x44, 0x45, 0x28, 0x8c, 0xb8, 0xc7, 0x19, 0x21, 0xf3, 0xd0,
	0x0e, 0xe7, 0x48, 0xb7, 0xea, 0x08, 0x33, 0x8c, 0x21, 0xc5, 0x92, 0xfa, 0x53, 0xaa, 0x7a, 0xf3,
	0x91, 0xf3, 0xa6, 0xce, 0xbc, 0x79, 0xbc, 0x8e, 0xe5, 0x42, 0x93, 0xaa, 0x27, 0x66, 0x67, 0x66,
	0x36, 0xae, 0x84, 0xba, 0xce, 0xe8, 0xe5, 0x71, 0x97, 0xed, 0x43, 0x7f, 0xee, 0x4a, 0x10, 0xdb,
	0xb0, 0x70, 0xed, 0xdf, 0x9c, 0xd9, 0x87, 0xd6, 0x31, 0xf6, 0x30, 0xc1, 0xa5, 0x37, 0x4b, 0xef,
	0x43, 0xf7, 0x10, 0xda, 0xcb, 0x5e, 0x20, 0x05, 0xe4, 0xac, 0xd6, 0xfe, 0x0f, 0x35, 0xa0, 0xc6,
	0xca, 0x6d, 0xa1, 0xff, 0x5d, 0x84, 0x6d, 0xbe, 0x93, 0xde, 0xcf, 0xc6, 0xfc, 0x3d, 0x43, 0x9d,
	0x75, 0xf4, 0xf9, 0x27, 0x53, 0x3b, 0xd8, 0xd0, 0x41, 0x1f, 0xc4, 0x77, 0x0c, 0xb1, 0xf8, 0x98,
	0xaf, 0x43, 0x9c, 0x3f, 0x0f, 0xda, 0xc3, 0x3f, 0xfb, 0x1c, 0xd0, 0x10, 0xb6, 0x0a, 0x23, 0xd0,
	0xdd, 0xdf, 0xbb, 0xa4, 0xdd, 0x5e, 0xb9, 0x54, 0x27, 0xd9, 0xff, 0x07, 0x3a, 0x05, 0x58, 0xc8,
	0x88, 0xd6, 0x52, 0xa9, 0xc8, 0x7c, 0x1d, 0x90, 0xd9, 0x7c, 0xdf, 0xc8, 0xc6, 0xd8, 0xd4, 0xa8,
	0xce, 0x0e, 0x9f, 0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x80, 0xcc, 0x23, 0xc7, 0xec, 0x06, 0x00,
	0x00,
}
